set AS=\TOOLS\MASM300

\TOOLS\TASM200 /Mx OSI_FILE;

%AS% /Mx KBD;

%AS% /Mx INFLATE;
\TOOLS\TASM200 /Mx MOUSE;
%AS% /Mx LOW;
%AS% /Mx DELAY;

%AS% /Mx DELAY2;
%AS% /Mx RAND;

%AS% /Mx SOUND1;
%AS% /Mx SOUND2;
%AS% /Mx SOUND3;
%AS% /Mx SOUND4;
%AS% /Mx SOUND5;

del OSISND.LIB
\TOOLS\TURBOC20\TLIB OSISND.LIB +SOUND1
\TOOLS\TURBOC20\TLIB OSISND.LIB +SOUND2
\TOOLS\TURBOC20\TLIB OSISND.LIB +SOUND3
\TOOLS\TURBOC20\TLIB OSISND.LIB +SOUND4
\TOOLS\TURBOC20\TLIB OSISND.LIB +SOUND5
REM \TOOLS\TURBOC20\TLIB OSISND.LIB +seg_33e3

set AS=
