#TLS = \RETRO\TOOLS
TLS = \TOOLS
TC = $(TLS)\TURBOC20
INCLUDE = $(TC)\INCLUDE
LIB = $(TC)\LIB
#AS = $(TLS)\tasm200
AS = $(TLS)\masm300
#AS = $(TLS)\masm400

OBJS = \
seg_0903.obj \
seg_0A33.obj \
seg_0C9C.obj \
seg_101C.obj \
seg_1100.obj \
seg_1184.obj \
seg_155X.obj \
seg_155D.obj \
seg_16E1.obj \
seg_1703.obj \
seg_1944.obj \
seg_1E0F.obj \
seg_2337.obj \
seg_27A1.obj \
seg_2E2D.obj \
seg_2F1A.obj \
seg_2FC1.obj \
seg_3200.obj \
seg_32C3.obj \
padding.obj seg_3522.obj seg_356A.obj \
D_2C4A.obj \
bss.obj

#osi_file.obj
#inflate.obj
#delay.obj
#mouse.obj
#low.obj
#kbd.obj
#delay2.obj
#rand.obj
#sound1.obj
#sound2.obj

all: game.exe
	$(TLS)\exepack game.exe game_.exe
	$(TLS)\unp game_.exe
	#copy game_.exe ..\game_.exe

#clean:
#	del game.exe
#	del ..\game_.exe
#	del *.obj

game.exe: $(OBJS)
	-tlink padding seg_3522 seg_356A $(LIB)\c0m @u6.lnk,game.exe,,$(LIB)\CM;

.c.obj:
	tcc -I$(INCLUDE) -d -mm -p -c -Z -O $<

padding.obj: padding.c
	tcc -I$(INCLUDE) -d -mh -p -c -Z -O padding.c

seg_3522.obj: seg_3522.c
	tcc -I$(INCLUDE) -d -mh -p -c -Z -O seg_3522.c

seg_356A.obj: seg_356A.c
	tcc -I$(INCLUDE) -d -mh -p -c -Z -O seg_356A.c

#osi_file.obj: osi_file.asm
#	$(TLS)\tasm200 /Mx osi_file,,;

bss.obj: bss.asm
	$(TLS)\tasm200 /Mx bss,,;

#mouse.obj: mouse.asm
#	$(TLS)\tasm200 /Mx mouse,,;

.asm.obj:
	$(AS) /Mx $<,,;
